### ISSUE TITLE
Client or server seems to truncate logs

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/snakepit#104]
See mozilla/snakepit-client#16

**Comment by reuben** [comment]
Also happens with downloads.

**Comment by tilmankamp** [comment]
@reuben Could you tell a bit about your observation(s)?

**Comment by reuben** [comment]
I get the same behavior as Kelly documented in mozilla/snakepit-client#16. `pit log` will show the logs, then it stops displaying new text, then after a few seconds the process ends without showing the full log. Right now it's happening for me on job 1244.

**Comment by tilmankamp** [comment]
@reuben How about the downloads?

**Comment by reuben** [comment]
Same thing, it starts downloading right away, then eventually the process ends without printing anything, and then when I try to extract the archive it's truncated.

**Comment by reuben** [comment]
One interesting thing is that (for `pit log` at least), the bug doesn't happen for finished jobs, only running ones.

**Comment by tilmankamp** [comment]
The download issue is very likely a totally different problem than the download one. At least they are to be fixed separately. So this one should be kept for the logs and #109 for the download problem.

**Comment by tilmankamp** [comment]
Most likely solved by virtual file-system approach. To be observed.
