### ISSUE TITLE
Lift or increase job description limit of 20 characters

### ISSUE THREAD

**Issue by reuben** [mozilla/snakepit#150]
It makes it super awkward to describe experiments, I have to make up my own shorthand and then I forget what it means.

**Comment by tilmankamp** [comment]
This requires defining a new practical size that would work well for the command line tool.

**Comment by reuben** [comment]
In https://github.com/mozilla/snakepit-client/pull/32 I propose truncating to 40 in the printouts.

**Comment by tilmankamp** [comment]
Fixed as #171
