### ISSUE TITLE
Self-signed certs used for transport

### ISSUE THREAD

**Issue by claudijd** [mozilla/snakepit#2]
Based on the setup script in https://github.com/mozilla/snakepit/blob/master/bin/setup.sh#L19, it appears as though this uses self-signed certs for transport.

Would maybe be better if the presumption is that valid certs were obtained and simply referenced their paths in the config?

**Comment by tilmankamp** [comment]
This is very early code and the setup script is primarily for dev/test/internal convenience.

**Comment by tilmankamp** [comment]
Kept this open for adding configurable certificate paths to the settings file.
