### ISSUE TITLE
Adding setup instructions to README

### ISSUE THREAD

**Issue by claudijd** [mozilla/snakepit#3]
I was looking into how to setup a local copy of this.

How would someone do that?  I expected something like a markdown doc or a wiki or page or something with steps to follow.

**Comment by claudijd** [comment]
I ended up just installing the node modules and then ran "node src/service.js" to get it up and running.

**Comment by tilmankamp** [comment]
This is very early code. Typically you'd use `npm install` after cloning and `npm start` to run.

**Comment by JRMeyer** [comment]
@tilmankamp - another doc ping for you here:)

**Comment by tilmankamp** [comment]
Done.
