### ISSUE TITLE
Note that bash read -i is not supported until bash 4.x

### ISSUE THREAD

**Issue by claudijd** [mozilla/snakepit#4]
I tried setting this up on my mac and happened to noticed -i wasn't introduced in bash until 4.x.

You may consider using something else to make it more compatible or making it more clear that bash 4.x is a requirement.

Article on Mac OSX bash read -i business: https://stackoverflow.com/questions/22634065/bash-read-command-does-not-accept-i-parameter-on-mac-any-alternatives

**Comment by tilmankamp** [comment]
Nice catch! Will fix it.

**Comment by tilmankamp** [comment]
With move to LXD there is no `read -i` anymore.
