### ISSUE TITLE
Cluster utilization monitoring

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/snakepit#40]
Replacement for `watch -n1 nvidia-smi` for all cluster nodes at once.

**Comment by tilmankamp** [comment]
@kdavis-mozilla I think for now we only need a list-like report of all GPUs on all nodes with GPU-utilization and memory-utilization. Anything else that should go into this?

**Comment by kdavis-mozilla** [comment]
@tilmankamp Those two, GPU-utilization and memory-utilization, seem like the top two to have.
