### ISSUE TITLE
Firejail blacklisting not reliable

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/snakepit#77]

**Comment by kdavis-mozilla** [comment]
Is this a result of NFS?

**Comment by tilmankamp** [comment]
Yes

**Comment by kdavis-mozilla** [comment]
What about alternatives like apparmor?

**Comment by tilmankamp** [comment]
Yes, this would be one of the alternatives I haven't tried yet.

**Comment by tilmankamp** [comment]
Will be fixed by moving to virtual FS and a different sandboxing solution.

**Comment by tilmankamp** [comment]
Will continue with this solution - still to be fixed.

**Comment by tilmankamp** [comment]
Solved by virtual file-system approach.
